name: HelloWorld

on:  
  push:
     branches:
       - main
       - develop
jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Download repo
        uses: actions/checkout@v4

      - name: Hello push ;-)
        run: echo "Hello world from push event on Github Actions ;-)"

      - name: Greet main branch 💻
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "Hello world from main branch! 💻"

      - name: Greet develop branch 🧪
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: echo "Hello world from develop branch! 🧪"
